services:
  identity-db:
    image: postgres:16
    environment: { POSTGRES_DB: identity, POSTGRES_USER: smartpay, POSTGRES_PASSWORD: local_dev_only }
    ports: ["5433:5432"]
    volumes: ["identity-data:/var/lib/postgresql/data"]
  wallet-db:
    image: postgres:16
    environment: { POSTGRES_DB: wallet, POSTGRES_USER: smartpay, POSTGRES_PASSWORD: local_dev_only }
    ports: ["5434:5432"]
    volumes: ["wallet-data:/var/lib/postgresql/data"]
  payment-db:
    image: postgres:16
    environment: { POSTGRES_DB: payment, POSTGRES_USER: smartpay, POSTGRES_PASSWORD: local_dev_only }
    ports: ["5435:5432"]
    volumes: ["payment-data:/var/lib/postgresql/data"]
  risk-db:
    image: postgres:16
    environment: { POSTGRES_DB: risk, POSTGRES_USER: smartpay, POSTGRES_PASSWORD: local_dev_only }
    ports: ["5436:5432"]
    volumes: ["risk-data:/var/lib/postgresql/data"]
  ledger-db:
    image: postgres:16
    environment: { POSTGRES_DB: ledger, POSTGRES_USER: smartpay, POSTGRES_PASSWORD: local_dev_only }
    ports: ["5437:5432"]
    volumes: ["ledger-data:/var/lib/postgresql/data"]
  notification-db:
    image: postgres:16
    environment: { POSTGRES_DB: notification, POSTGRES_USER: smartpay, POSTGRES_PASSWORD: local_dev_only }
    ports: ["5438:5432"]
    volumes: ["notification-data:/var/lib/postgresql/data"]
  rabbitmq:
    image: rabbitmq:3-management
    environment: { RABBITMQ_DEFAULT_USER: smartpay, RABBITMQ_DEFAULT_PASS: local_dev_only }
    ports: ["5672:5672", "15672:15672"]
volumes:
  identity-data:
  wallet-data:
  payment-data:
  risk-data:
  ledger-data:
  notification-data:
